// Auto-generated by cdm install -- do not edit
import type { HexString, Binary, FixedSizeBinary } from "polkadot-api";

declare module "@dotdm/cdm" {
    interface CdmContracts {
        "@polkadot/contexts": {
            methods: {
                registerContext: { args: [context_id: FixedSizeBinary<32>]; response: undefined };
                getOwner: { args: [context_id: FixedSizeBinary<32>]; response: HexString };
                isOwner: { args: [context_id: FixedSizeBinary<32>, address: HexString]; response: boolean };
            };
        };
    }
}
